letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./certificates:/etc/nginx/certs:rw
  volumes_from:
    - nginx

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./certificates:/etc/nginx/certs:ro
    - ./nginx/vhost.d:/etc/nginx/vhost.d
    - ./nginx/html:/usr/share/nginx/html
  ports:
    - 443:443
    - 80:80
  links:
    - hackmd

hackmdPostgres:
  image: postgres:9.5
  volumes:
    - /container-data/metabase/dumps:/dumps
    - /container-data/metabase/pgdata:/pgdata
  environment:
    - PGDATA=/pgdata
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
    - POSTGRES_DB=hackmd

hackmd:
  # image: hackmdio/hackmd:0.4.4
  build: hackmd
  environment:
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
    - VIRTUAL_HOST=hackmd.loomio.io
    - LETSENCRYPT_HOST=hackmd.loomio.io
    - LETSENCRYPT_EMAIL=devops@loomio.org
  links:
    - hackmdPostgres
  ports:
    - "3000:3000"
